### PR TITLE
Fixed Logo and Names Fixed the #5 issues and #10 issues 

### LINKED ISSUE #5: Refactoring branding
This project was made as a part of Microsoft engage program , so it specifies Microsoft teams clone . So , the branding needs to be changed , i.e , the logo and name must be changed everywhere in the project .

### LINKED ISSUE #10: Removing build checks
Remove github workflows .

### PR DESCRIPTION
**Pull request by koushikpuppala**
Fixing the Issue #5 
Fixing the Issue #10 
I have updated the Name and Logo of the app

### CODE REVIEW

**Comment by koushikpuppala** [comment]
@5h0bh4nk Check this

**Comment by koushikpuppala** [comment]
@5h0bh4nk I have updated #10 also

**Comment by 5h0bh4nk** [comment]
Nice work @koushikpuppala 
Thanks for your contribution !!

**Review by 5h0bh4nk — APPROVED** [review]
Reviewed and tested .

**Pull request merged**
